# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 871361a29d217ebfca894421ac070019d5c89ad5201a22080ca096acc3b5f9525950981d44313893b2b9d6fc1ef81c4ecaaeec06f87a98d1b4319e81c0de481e

test:
  secret_key_base: e34e2266e685f49ed119acb6f71f6f0a56ac43b7c8faf2008518c0d8e21b0524c277f7429a3dd75a9acb06fe7b5719abdacb95e47ce816527c1e8dc1ba5cd582

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
